// <auto-generated />
using System;
using Bank_Accounts.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bank_Accounts.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190411003530_SeMigration")]
    partial class SeMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bank_Accounts.Models.ForLandR", b =>
                {
                    b.Property<int>("ForLandRId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Firstname")
                        .IsRequired();

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("ForLandRId");

                    b.ToTable("ForLandRes");
                });

            modelBuilder.Entity("Bank_Accounts.Models.Transaction", b =>
                {
                    b.Property<int>("TansactionId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("ForLandRId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("TansactionId");

                    b.HasIndex("ForLandRId");

                    b.ToTable("Transactiones");
                });

            modelBuilder.Entity("Bank_Accounts.Models.Transaction", b =>
                {
                    b.HasOne("Bank_Accounts.Models.ForLandR", "Customer")
                        .WithMany("Trans")
                        .HasForeignKey("ForLandRId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
